### ISSUE TITLE
Faraday 2 upgrade is incompatible with Faraday 1.x

### ISSUE THREAD

**Issue by mwpastore** [taylorbrooks/closeio#78]
FYI, this gem is now incompatible with Faraday 1.x, so the gemspec should make Faraday 2.x a requirement. 

```
2023-04-25T16:24:27.666278+00:00 app[worker.1]: pid=2 tid=93a WARN: ArgumentError: wrong number of arguments (given 4, expected 3)
2023-04-25T16:24:27.666310+00:00 app[worker.1]: pid=2 tid=93a WARN: /app/vendor/bundle/ruby/3.1.0/gems/faraday-1.10.3/lib/faraday/request/authorization.rb:48:in `initialize'
2023-04-25T16:24:27.666311+00:00 app[worker.1]: /app/vendor/bundle/ruby/3.1.0/gems/faraday-1.10.3/lib/faraday/dependency_loader.rb:23:in `new'
2023-04-25T16:24:27.666311+00:00 app[worker.1]: /app/vendor/bundle/ruby/3.1.0/gems/faraday-1.10.3/lib/faraday/dependency_loader.rb:23:in `new'
2023-04-25T16:24:27.666311+00:00 app[worker.1]: /app/vendor/bundle/ruby/3.1.0/gems/faraday-1.10.3/lib/faraday/rack_builder.rb:57:in `build'
2023-04-25T16:24:27.666311+00:00 app[worker.1]: /app/vendor/bundle/ruby/3.1.0/gems/faraday-1.10.3/lib/faraday/rack_builder.rb:175:in `block in to_app'
2023-04-25T16:24:27.666312+00:00 app[worker.1]: /app/vendor/bundle/ruby/3.1.0/gems/faraday-1.10.3/lib/faraday/rack_builder.rb:174:in `each'
2023-04-25T16:24:27.666312+00:00 app[worker.1]: /app/vendor/bundle/ruby/3.1.0/gems/faraday-1.10.3/lib/faraday/rack_builder.rb:174:in `inject'
2023-04-25T16:24:27.666312+00:00 app[worker.1]: /app/vendor/bundle/ruby/3.1.0/gems/faraday-1.10.3/lib/faraday/rack_builder.rb:174:in `to_app'
2023-04-25T16:24:27.666312+00:00 app[worker.1]: /app/vendor/bundle/ruby/3.1.0/gems/faraday-1.10.3/lib/faraday/rack_builder.rb:167:in `app'
2023-04-25T16:24:27.666312+00:00 app[worker.1]: /app/vendor/bundle/ruby/3.1.0/gems/faraday-1.10.3/lib/faraday/rack_builder.rb:154:in `build_response'
2023-04-25T16:24:27.666313+00:00 app[worker.1]: /app/vendor/bundle/ruby/3.1.0/gems/faraday-1.10.3/lib/faraday/connection.rb:516:in `run_request'
2023-04-25T16:24:27.666313+00:00 app[worker.1]: /app/vendor/bundle/ruby/3.1.0/gems/faraday-1.10.3/lib/faraday/connection.rb:202:in `get'
2023-04-25T16:24:27.666313+00:00 app[worker.1]: /app/vendor/bundle/ruby/3.1.0/gems/closeio-3.14.0/lib/closeio/client.rb:45:in `get'
2023-04-25T16:24:27.666313+00:00 app[worker.1]: /app/vendor/bundle/ruby/3.1.0/gems/closeio-3.14.0/lib/closeio/resources/contact.rb:9:in `find_contact'
```

**Comment by mwpastore** [comment]
https://github.com/lostisland/faraday/blob/main/docs/middleware/request/authentication.md

**Comment by taylorbrooks** [comment]
@mwpastore @atyndall

Does this work? https://github.com/taylorbrooks/closeio/blob/master/closeio.gemspec#L21

The latest gem (3.15.0) should've caught this.

**Comment by atyndall** [comment]
@taylorbrooks yes, I believe it does. We've had to blacklist two versions of the gem in our gemfile, as they break things;
```ruby
gem 'closeio', '!= 3.14.0', '!= 3.13.0'
```
but now it stays at 3.12.0 as it correctly determines that 3.15.0 is incompatible with our faraday 1 dependency.

**Comment by taylorbrooks** [comment]
I'll yank those versions from Rubygems.

**Comment by mwpastore** [comment]
LGTM! Thank you!

**Comment by taylorbrooks** [comment]
Awesome. Apologies for screwing this up. :)

Closing...

**Comment by mwpastore** [comment]
No worries, it was easy enough to troubleshoot and work around on my end. Thank you for all your hard work on this gem!
